
  
trigger:
  - master
jobs:
  - job: 'test_dashboard'
    pool:
      vmImage: 'Ubuntu-16.04'
    timeoutInMinutes: 0
    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - bash: bash ./ci/install.sh
        displayName: Create conda env
      - bash: |
          source activate testenv
          echo "DEV is set to $DEV"
          R -e "shiny::runApp('.')"
        displayName: Test scripts
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
          DEV: True
  - job: 'test_notebooks'
    pool:
      vmImage: 'Ubuntu-16.04'
    timeoutInMinutes: 0
    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - bash: bash ./ci/install.sh
        displayName: Create conda env
      - bash: |
          source activate testenv
          echo "DEV is set to $DEV"
          make -C notebooks
        displayName: Test notebooks
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
          DEV: True